### ISSUE TITLE
[2018.2.167] Track download button is missing from the DOM (Premium Account)

### ISSUE THREAD

**Issue by domdorn** [lethak/digitally_imported_userscript#17]
I just wanted to check why the download button disappeared and noticed, that you're now obfuscating the source... why?!

**Comment by lethak** [comment]
Hi,
What do you mean by "the download button disappeared ?"
All current and previous releases are still there https://github.com/lethak/LTKDIFMU-userscript/releases

As for the obfuscation, its simply minified and packaged using automated tools like babel and webpack to dramatically reduce the script size since I started including a lot of library to start building a more complex framework for future ideas I would like to add. (I will publish the code base later when its completed, and it will be on another repository)

If you wish to fork the project you can do so using this tag prior to minification https://github.com/lethak/LTKDIFMU-userscript/tree/v2018.1.4b

**Comment by domdorn** [comment]
![image](https://user-images.githubusercontent.com/100349/37253053-b4b69a0a-252c-11e8-9d4b-5b7e0c15e916.png)
the download button in this screenshot disappeared. 

as for minification: It would be great if you could still also provide the unminified source in the repository. 
this would get experienced users the chance to debug issues themselves and provide contributions to your user-script. 
it would also give me the peace of mind, that my credentials are not sent-out to another website, as I can look through the code and see whats going on. 

Thanks,
Dominik

**Comment by lethak** [comment]
Ah this download button ! :D  this seems to be missing indeed ! I will take a look

**Comment by lethak** [comment]
It seems the di player's DOM was updated, and the userscript was not able to find a suitable container to add the button to. I will add an error console message if no suitable DOM container can be found for future iterations of this event.

Fixed in: https://github.com/lethak/LTKDIFMU-userscript/releases/tag/v2018.3.4

**Comment by domdorn** [comment]
Hi.. this issue reappeared for me

**Comment by lethak** [comment]
Hi, I have not worked on this for a while but everything is still working as intended from my side, do you have more details ? browser, userscript loader, versions, etc. (open a new issues with steps to reproduce)
thanks

**Comment by domdorn** [comment]
![image](https://user-images.githubusercontent.com/100349/42226585-940a58de-7edf-11e8-94bb-5964c8974edb.png)
![image](https://user-images.githubusercontent.com/100349/42226604-a10f3e32-7edf-11e8-9f7e-97966777cd2c.png)
![image](https://user-images.githubusercontent.com/100349/42226645-c05841d0-7edf-11e8-8b48-b83aad42e04f.png)

**Comment by lethak** [comment]
Thanks. Indeed something changed on DI's side for Premium Accounts, I'll look into it soon

**Comment by domdorn** [comment]
thanks!

**Comment by lethak** [comment]
Do you have an error in the javascript console ?

> Cannot find a suitable DOM container to inject the download button

**Comment by domdorn** [comment]
I'm having this one when loading the page
![image](https://user-images.githubusercontent.com/100349/42294561-38b63d50-7fe2-11e8-8a8a-ea038f2ea80f.png)

I also noticed that sometimes the Download Icon is there, and sometimes it disappears (e.g. when switching to another channel) .. however, there's nothing logged in the console. 

A "workaround" seems to be to switch to a channel that has a live-show running.. after that, the download button appears, then I can switch to other channels and the download button also appears.. after some clicking around (switching channels) it disappears again and I have to switch to a live-channel.. If I'd have to guess, i'd look for some global state?

**Comment by lethak** [comment]
Let me know if v2018.7.1 fixed your problem.

If not, you should have new console errors to forward here ;)

**Comment by domdorn** [comment]
hmm.. its still somehow flacky.. sometimes works, other times not.. exception looks the same as before.. ( I checked that I'm now using 2018.7.1 ) 
![image](https://user-images.githubusercontent.com/100349/42315189-179bafa0-8047-11e8-9ad4-e754f798576f.png)

is there a way I can debug it?

**Comment by lethak** [comment]
Alright, I was lazy and did not compensated properly for the "index 95" error (I could have..) will do soon.
This error means the DI request/responder `webplayer:ads:shouldShowMidroll` is missing.
This error is only showing with premium accounts, and I have no such account available to test atm.
So, thank you for helping.

can you try in the console:
```javascript
di.app.request('webplayer:ads:shouldShowMidroll')
```
what is the outpout ?

**Comment by lethak** [comment]
Alright, give it a new try

**Comment by domdorn** [comment]
please drop me a short mail at dominik at dominikdorn dot com ...

**Comment by lethak** [comment]
I am not using any emails; you can add me on discord if you want `LethaK#5913`

**Comment by domdorn** [comment]
by discord you mean https://discordapp.com/ ?

**Comment by domdorn** [comment]
ok... https://github.com/domdorn/lethak-secret

**Comment by lethak** [comment]
discordapp indeed, sorry i thought this was obvious :)

**Comment by lethak** [comment]
fixed in v2018.7.5 (commit message stating 2018.7.8 is a mistake)

Thanks for your help

**Comment by domdorn** [comment]
I'm still having the issue when continuing my stream on "Big Room House" which continues in the last song
![image](https://user-images.githubusercontent.com/100349/42397316-be2d8afe-8165-11e8-8040-35c08bdb5ada.png)

**Comment by lethak** [comment]
This is another problem altogether based on your connection being too slow at loading the track. (#19)

I'll find something to solve this

**Comment by domdorn** [comment]
hmm.. I have a 100mbit+ connection here, so connection speed shouldn't be a problem.. are you adding the download track button only when the track is loaded? the url is in the json response of the channel xhr request
![image](https://user-images.githubusercontent.com/100349/42398557-94212c70-816a-11e8-8202-a4584b649f17.png)

**Comment by lethak** [comment]
Fixed as of 0254dd3fda4556ca0dcddcbeefe036f2741bed8a (v2020.3.429) (better late than never :))
